version: '3.9'

services:
  api:
    ports:
      # Exposes application port.
    - "8000:8000"
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      ENSEMBL-METADATA-API_RELOAD: "True"
